services:
  parts_website:
    container_name: ${CONTAINER_NAME}
    image: bduke97/parts_website:${TAG}
    ports:
      - "8078:80"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: false
    # Health check configuration
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
