services:
  parts_website:
    container_name: ${CONTAINER_NAME}
    image: bduke97/parts_website:latest
    ports:
      - "8078:80"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: false
