version: "3.8"

services:
  parts_webapi:
    container_name: ${CONTAINER_NAME}
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      FRONTEND_ADDRESS: ${FRONTEND_ADDRESS}
      DISCORD_NOTIFICATION_WEBHOOK: ${DISCORD_NOTIFICATION_WEBHOOK}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      DEBUG: ${DEBUG}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "${API_PORT}:9090"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: false
