version: "2"

services:
  parts_website:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8078:80"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: false
